# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Website Only
#  See ../Docs/Create-Variable-Group.md for for info about variable group "IoTDemo"
# ------------------------------------------------------------------------------------------------------------------------
name: $(Build.DefinitionName).$(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
      - Dashboard
    exclude: 
      - '**/*.yml'
      - '**/*.bicep'
      - '**/*.md'

pool:
  vmImage: windows-latest

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/website-only-pipeline-template.yml
  parameters:
    variableGroupName: 'IoTDemo'
    folderName: 'IoT.Dashboard'
    projectName: 'IoT.Dashboard'
    webAppName: 'Dashboard'
    environments: ['DEV','PROD']  # ['DEV'] or ['DEV','QA'] or ['DEV','QA','PROD']
