# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build IoT Simulator; compiles for both Windows (x64) and Linux; copies EXE to storage for downloading ease
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "IoTDemo"
#  See ./Docs/Create-Variable-Group.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: 'windows-latest'

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  branches:
    include: 
      - main
  paths:
    include:
      - Simulator
    exclude: 
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.bicep'

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: deployToStorage
    displayName: Copy To Storage Account
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/console-app-pipeline-template.yml
  parameters:
    variableGroupName: 'IoTDemo'
    environments: ['DEMO']  # ['DEV','PROD'] ['DEV','QA'] or ['DEV','QA','PROD']
    deployToStorage: ${{ parameters.deployToStorage }}

