# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Website Only
#  See ./Docs/Create-Variable-Group.md for for info about variable group "IoTDemo"
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

pool:
  vmImage: 'windows-latest'

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
      - Dashboard
    exclude: 
      - '**/*.yml'
      - '**/*.bicep'
      - '**/*.md'

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: runDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false
  - name: runPsRuleScan
    displayName: Run PSRule Bicep Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/website-only-pipeline-template.yml
  parameters:
    variableGroupName: 'IoTDemo'
    folderName: 'Dashboard'
    projectName: 'IoT.Dashboard'
    webAppName: 'Dashboard'
    environments: ['DEMO']  # ['DEV','PROD'] ['DEV','QA'] or ['DEV','QA','PROD']
    runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
    runPsRuleScan: ${{ parameters.runPsRuleScan }}