# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build application and deploy it to multiple optional environments
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: variableGroupName
  default: 'myVariableGroupName'
- name: folderName
  default: ''
- name: projectName
  default: ''
- name: webAppName
  default: ''
- name: runDevSecOpsScan
  default: 'true'
- name: runPsRuleScan
  default: 'true'

# ----------------------------------------------------------------------------------------------------
stages:
- stage: BuildWebApp
  displayName: Build Web App
  jobs:
  - ${{ if or(eq(lower(parameters.runDevSecOpsScan), 'true'), eq(lower(parameters.runPsRuleScan), 'true')) }}:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEV'
        runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
        runPsRuleScan: ${{ parameters.runPsRuleScan }}

  - template: templates/build-website-template.yml
    parameters:
      variableGroupName: ${{ parameters.variableGroupName }}
      environmentName: 'DEV'
      folderName: ${{ parameters.folderName }}
      projectName: ${{ parameters.projectName }}

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: DeployWebsite${{ environmentName }}
    displayName: Deploy ${{ environmentName }} Website
    jobs:
    - template: templates/deploy-website-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: ${{ environmentName }}
        folderName: ${{ parameters.folderName }}
        projectName: ${{ parameters.projectName }}
        webAppName: ${{ parameters.webAppName }}