# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources for All Environments for the IoT Demo Project
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "IoTDemo-<env>" -> one for EACH environment being deployed.
#  See ../Docs/VariableGroups.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  paths:
    include: 
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.bicep'

# ----------------------------------------------------------------------------------------------------
stages:
- stage: DeployDEVResources
  displayName: DEV Deploy Resources
  jobs:
  - template: templates\create-infra.yml
    parameters:
      variableGroupName: 'IoTDemo-Dev'
      environmentName: 'DEV'
      runDateTime: 'Pipeline-$(Build.BuildNumber)'

# ----------------------------------------------------------------------------------------------------
- stage: DeployQAResources
  displayName: QA Deploy Resources
  dependsOn: DeployDEVResources
  condition: succeeded('DeployDEVResources')
  jobs:
  - template: templates\create-infra.yml
    parameters:
      variableGroupName: 'IoTDemo-QA'
      environmentName: 'QA'
      runDateTime: 'Pipeline-$(Build.BuildNumber)'
