# ----------------------------------------------------------------------------------------------------
# Template to build Azure Function and create artifacts
# ----------------------------------------------------------------------------------------------------
parameters: 
- name: variableGroupName
  default:  'myVariableGroup'
- name: environmentName
  default:  'DEV'

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: InitializeBuild${{ parameters.environmentName }}Function
  displayName: Initialize ${{ parameters.environmentName }} Build Function
  environment: ${{ parameters.environmentName }}

- job: Build${{ parameters.environmentName }}Function
  displayName: Build ${{ parameters.environmentName }} Function

  variables:
    - group: ${{ parameters.variableGroupName }}
    - name: workingDirectory
      value: '$(System.DefaultWorkingDirectory)/FunctionApp/IoT.Processor'

  steps:
  - task: CmdLine@2
    inputs:
      script: |
        echo "Build.ArtifactStagingDirectory=$(Build.ArtifactStagingDirectory)"
        echo "System.DefaultWorkingDirectory=$(System.DefaultWorkingDirectory)"
        echo "Build.BuildId=$(Build.BuildId)"
        echo "appPrefix=$(appPrefix)"
        tree $(System.DefaultWorkingDirectory)
        dir $(System.DefaultWorkingDirectory) /s
      continueOnError: true
      displayName: 'Display Variables'

  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      command: build
      projects: $(workingDirectory)/*.csproj
      arguments: --output $(System.DefaultWorkingDirectory)/function_output --configuration Release

  - task: ArchiveFiles@2
    displayName: 'Zip Output'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/function_output'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/function-$(appPrefix)$(Build.BuildId).zip
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: functiondrop
      publishLocation: 'pipeline'

  - task: CmdLine@2
    inputs:
      script: |
        tree $(workingDirectory)
        tree $(Build.ArtifactStagingDirectory)
    displayName: 'Display Directory Tree'


